### ISSUE TITLE
User avatar shows white frame

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-screensaver#8] opened 2020-02-12 09:33 UTC
锁屏界面，用户头像为白框

On the lock screen, the user avatar is a white frame

**Comment by liuyuanpeng176** [comment] 2020-03-14 09:45
已修复，使用默认的头像

**Comment by xiaodongliu-nudt** [comment] 2020-03-21 02:38
Duplicate of #7

**Closed as completed by xiaodongliu-nudt** 2020-03-21 02:38 UTC
Labels: resolved
